metadata:
- appName: ''
  dataId: shared-jdbc.yaml
  desc: jdbc相关共享配置
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: shared-log.yaml
  desc: 日志共享配置
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: shared-swagger.yaml
  desc: swagger共享配置
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: cart-service.yaml
  desc: 购物车服务的默认配置
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: gateway-routes.json
  desc: 动态路由
  group: DEFAULT_GROUP
  type: json
- appName: ''
  dataId: shared-seata.yaml
  desc: 共享seata配置
  group: DEFAULT_GROUP
  type: yaml
